import Head from 'next/head'
import {Header} from '../components/Header'

export default function Home({handleThemeSwitch, currentTheme}: {handleThemeSwitch: React.MouseEventHandler<HTMLButtonElement>, currentTheme: string}) {
  return (
    <>
      <Head>
        <title>Blog articles</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header currentTheme={currentTheme} handleThemeSwitch={handleThemeSwitch} />
      </main>
    </>
  )
}
